version: '3'

services:
    fm-api-image:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DB_HOST=postgres
            - DB_NAME=postgres
            - DB_USERNAME=username
            - DB_PASSWORD=password
            - ACCESS_TOKEN_SECRET=accesstoken
            - REFRESH_TOKEN_SECRET=refreshtoken
        container_name: 'fm-api-container'
        restart: always
        ports:
            - '4000:4000'
    postgres:
        container_name: postgres_db
        image: postgres
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'
        restart: always
    graphql-engine:
        image: hasura/graphql-engine:v2.8.4.cli-migrations-v3
        ports:
            - '8080:8080'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - 'postgres'
        restart: always
        volumes:
            - ./hasura/migrations:/hasura/migrations
            - ./hasura/metadata:/hasura-metadata
        environment:
            HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://username:password@postgres:5432/postgres
            HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
            HASURA_GRAPHQL_DEV_MODE: 'true'
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
volumes:
    db_data:
