version: '3'

services:
    fm-api-image:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DB_HOST=postgres
            - DB_NAME=postgres
            - DB_USERNAME=username
            - DB_PASSWORD=password
            - ACCESS_TOKEN_SECRET=accesstoken
            - REFRESH_TOKEN_SECRET=refreshtoken
        container_name: 'fm-api-container'
        restart: always
        ports:
            - '4000:4000'
    postgres:
        container_name: postgres_db
        image: postgres
        environment:
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'
